# Generated by Django 5.0.2 on 2024-03-19 05:32

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_text', models.TextField()),
            ],
            def set_default_age(apps, schema_editor):
                Question = apps.get_model('yourappname', 'Question')
                Question.objects.filter(age='').update(age=3)  # Set default value for existing records

            class Migration(migrations.Migration):

                dependencies = [
                  ('yourappname', 'previous_migration'),
                         ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='age',
            field=models.IntegerField(choices=[(3, '3 years old'), (4, '4 years old'), (5, '5 years old'), (6, '6 years old'), (7, '7 years old'), (8, '8 years old')], default=3),
            preserve_default=False,  # Remove this line if using a default value
        ),
        migrations.RunPython(set_default_age),
    ]

        ),
    


    ]
