# Generated by Django 5.0.2 on 2024-03-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Addition', '+'), ('Subtraction', '-')], default='General', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
