# Generated by Django 5.0.2 on 2024-03-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0003_question_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='age',
            field=models.CharField(choices=[('3', '3 years old'), ('4', '4 years old'), ('5', '5 years old'), ('6', '6 years old'), ('7', '7 years old'), ('8', '8 years old')], default='3', max_length=2),
        ),
    ]
