# Generated by Django 5.0.2 on 2024-03-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0007_alter_question_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Shapes', '#'), ('Addition', '+'), ('Subtraction', '-'), ('Multiplication', '*'), ('Divison', '/')], default='General', max_length=200),
        ),
    ]
