# Generated by Django 5.0.2 on 2024-03-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0008_alter_question_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_text',
            new_name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='', upload_to='question_images/'),
            preserve_default=False,
        ),
    ]
