# Generated by Django 5.0.2 on 2024-03-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0009_rename_answer_text_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=255)),
                ('answer_choice1', models.CharField(max_length=255)),
                ('answer_choice2', models.CharField(max_length=255)),
                ('answer_choice3', models.CharField(max_length=255)),
                ('answer_choice4', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='', upload_to='question_images/'),
        ),
    ]
